### ISSUE TITLE
Migration to the modern `elab-util` version

### ISSUE THREAD

**Issue by buzden** [buzden/deptycheck#136]
Currently an old [pre-overhaul](https://github.com/stefan-hoeck/idris2-elab-util/pull/56) version of the `elab-util` library is used. I tried to migrate in a single hop a lot of times, but didn't even manage to finish. Currently, I see the migration to be possible in the following steps:
- [x] Copying old pre-overhaul parts of `Language.Reflection.Types` into DepTyCheck (with permission of Stefan) and switching to them (#137);
- [x] Removing special fork from `pack.toml` (#137);
- [x] Using modern pretty-printer from `elab-pretty` library (#137);
- [x] Switching from `Arg True` to `Arg False` everywhere possible to smoothen transition to modern unparametesired `Arg` (#138);
- [x] Switching from outdated `Arg True` (aka `NamedArg`) type to moder `Arg` type and `NamedArg` predicate (#138);
- [ ] Moving to the modern indexed `Con` and `TypeInfo`.

**Comment by buzden** [comment]
The last item is not planned for now, so closing
