### ISSUE TITLE
Use `pack` for building instead of custom build system and submodules with dependencies

### ISSUE THREAD

**Issue by buzden** [buzden/deptycheck#27]
[`pack`](https://github.com/stefan-hoeck/idris2-pack) is a modern, cool and convenient way to do what we were doing in an ad-hoc way

May contain as substeps:
- [x] Usage of `pack` in CI for selection of particular Idris version instead of custom `.idris-version` file (#45)
- [x] Usage of `pack` for installing external libraries like `elab-util` and `summary-stat` in `Makefile`, thus removing top-level `depends` dir (#48)
- [x] Usage of `pack` for building `deptycheck` itself (#48)
- [x] Usage of `pack` for finding built `deptycheck` from tests, thus getting rid of ubiquitous `depends` dirs in `tests` (#48)
- [x] Move all `installation` tests to other sections (#48)
- [x] Make use of `golden-runner-helper` to run tests with `pack test ...` (#49)
- [x] Remove makefiles (#48, #49)
- [x] Usage of smaller libraries like `if-implicit-unsolved` and `mtl-tupled-impls` instead of actually having their modules here (#50)
- [x] Moving small common definitions for testing to small libraries with local `pack.toml`s instead of ubiquitous symlinks to the common files (#342)
